apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:5.6.4
          ports:
            - containerPort: 5601
          env:
            - name: "ELASTICSEARCH_URL"
              value: "http://elasticsearch:9200"
            - name: "elasticsearch.username"
              value: "elastic"
            - name: "elasticsearch.password"
              value: "changeme"
