apiVersion: apps/v1
kind: Deployment
metadata:
  name: person
  labels:
    app: person
spec:
  replicas: 5
  selector:
    matchLabels:
      app: person
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: person
    spec:
      containers:
        - name: person
          image: person/api:16-12
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: 128Mi
            requests:
              cpu: "0.5"
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
