apiVersion: v1
kind: Service
metadata:
  name: person-svc
  namespace: default
  labels:
    app: person
spec:
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 80
  selector:
    app: person
  type: LoadBalancer
