apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: chronos
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
          ports:
            - containerPort: 9300
            - containerPort: 9200
          env:
            - name: "http.cors.enabled"
              value: "true"
            - name: "http.cors.allow-origin"
              value: "*"
          volumeMounts:
            - mountPath: "/usr/share/elasticsearch/data"
              name: elasticsearch
      volumes:
        - name: elasticsearch
          emptyDir: {}
