version: "3.1"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  grafana:
    image: grafana/grafana:4.6.1
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: changeme
    volumes:
      - gfdata:/var/lib/grafana
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.4
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      elasticsearch.username: elastic
      elasticsearch.password: changeme

volumes:
  esdata:
    driver: local
  gfdata:
    driver: local
