apiVersion: apps/v1
kind: Deployment
metadata:
  name: requester
  namespace: chronos
  labels:
    app: requester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requester
  template:
    metadata:
      labels:
        app: requester
    spec:
      containers:
        - name: requester
          image: requester/app:22-06
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: requester-configmap
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
