apiVersion: apps/v1
kind: Deployment
metadata:
  name: person
  labels:
    app: person
spec:
  replicas: 3
  selector:
    matchLabels:
      app: person
  template:
    metadata:
      labels:
        app: person
    spec:
      containers:
        - name: person
          image: person/api:15-34
          ports:
            - containerPort: 80
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ConnectionStrings__DefaultConnection
              value: "Server=database;Database=master;User=sa;Password=Your_password123;"
          resources:
            requests:
              cpu: "2"
              memory: "512M"
            limits:
              cpu: "6"
              memory: "1G"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
