apiVersion: v1
kind: Service
metadata:
  name: person
  namespace: default
  labels:
    app: person
spec:
  selector:
    app: person
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 80
