version: "3.1"

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.4
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      elasticsearch.username: elastic
      elasticsearch.password: changeme
