apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: chronos
  labels:
    app: kibana
spec:
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  selector:
    app: kibana
  type: LoadBalancer
