apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: "9300-port"
      port: 9300
      targetPort: 9300
    - protocol: TCP
      name: "9200-port"
      port: 9200
      targetPort: 9200
