apiVersion: apps/v1
kind: Deployment
metadata:
  name: requester
  labels:
    app: requester
spec:
  replicas: 2
  selector:
    matchLabels:
      app: requester
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: requester
    spec:
      containers:
        - name: requester
          image: requester/app:00-44
          ports:
            - containerPort: 80
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ConnectionStrings__DefaultConnection
              value: "Server=database;Database=master;User=sa;Password=Your_password123;"
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   initialDelaySeconds: 3
          #   periodSeconds: 5
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 80
          #   initialDelaySeconds: 3
          #   periodSeconds: 5
          #   failureThreshold: 3
