apiVersion: apps/v1
kind: Deployment
metadata:
  name: person
  namespace: chronos
  labels:
    app: person
spec:
  replicas: 2
  selector:
    matchLabels:
      app: person
  template:
    metadata:
      labels:
        app: person
    spec:
      containers:
        - name: person
          image: person/api:22-26
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: person-configmap
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: "250m"
              memory: "128M"
            limits:
              cpu: "1000m"
              memory: "512M"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
