apiVersion: v1
kind: Service
metadata:
  name: person
  namespace: chronos
  labels:
    app: person
spec:
  selector:
    app: person
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
